// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import fs from "fs";
import path from "path";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

const envCandidates = [".env.local", ".env.development.local", ".env"];
const envPath = envCandidates.find((file) => fs.existsSync(path.resolve(file)));

if (envPath) {
  dotenv.config({ path: envPath });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
